export const PRODUCT_SIZES = ['S', 'M', 'L', 'XL', 'XXL'];
export const PRODUCT_COLORS = [
  {
    name: 'purple',
    value: 'bg-product-color-purple',
    border: 'border-product-color-purple',
    color: '#8434e1',
    label: 'Purple',
  },
  {
    name: 'black',
    value: 'bg-product-color-black',
    border: 'border-product-color-black',
    color: '#252525',
    label: 'Black',
  },
  {
    name: 'red',
    value: 'bg-product-color-red',
    border: 'border-product-color-red',
    color: '#f35528',
    label: 'Red',
  },
  {
    name: 'orange',
    value: 'bg-product-color-orange',
    border: 'border-product-color-orange',
    color: '#f16f2b',
    label: 'Orange',
  },
  {
    name: 'navy',
    value: 'bg-product-color-navy',
    border: 'border-product-color-navy',
    color: '#345eff',
    label: 'Navy',
  },
  {
    name: 'white',
    value: 'bg-product-color-white',
    border: 'border-product-color-white',
    color: '#f4f1f1',
    label: 'White',
  },
  {
    name: 'broom',
    value: 'bg-product-color-broom',
    border: 'border-product-color-broom',
    color: '#d67e3b',
    label: 'Broom',
  },
  {
    name: 'green',
    value: 'bg-product-color-green',
    border: 'border-product-color-green',
    color: '#48bc4e',
    label: 'Green',
  },
  {
    name: 'yellow',
    value: 'bg-product-color-yellow',
    border: 'border-product-color-yellow',
    color: '#fdc761',
    label: 'Yellow',
  },
  {
    name: 'grey',
    value: 'bg-product-color-grey',
    border: 'border-product-color-grey',
    color: '#e4e5e8',
    label: 'Grey',
  },
  {
    name: 'pink',
    value: 'bg-product-color-pink',
    border: 'border-product-color-pink',
    color: '#e08d9d',
    label: 'Pink',
  },
  {
    name: 'blue',
    value: 'bg-product-color-blue',
    border: 'border-product-color-blue',
    color: '#3fdeff',
    label: 'Blue',
  },
];
